_wandb:
    value:
        cli_version: 0.23.0
        e:
            zxt0iwjq8y7tam46u9cb5clnn6qihimn:
                args:
                    - --mode
                    - train
                    - --train_data
                    - data/tiny_stories_train.bin
                    - --val_data
                    - data/tiny_stories_val.bin
                    - --max_iters
                    - "2"
                    - --cosine_cycle_iters
                    - "2"
                codePath: cs336_basics/run.py
                codePathLocal: run.py
                email: lilyxsu@gmail.com
                executable: /Users/lilysu/anaconda3/bin/python
                git:
                    commit: 3a04feb9ba35f24679cd9b0685b5adc0cdc412b5
                    remote: git@github.com:LilySu/stanford-cs366-assignments.git
                host: Lilys-Laptop.local
                os: macOS-15.1-arm64-arm-64bit
                program: /Users/lilysu/Documents/git/assignment1-basics/cs336_basics/run.py
                python: CPython 3.11.5
                root: /Users/lilysu/Documents/git/assignment1-basics/cs336_basics
                startedAt: "2025-11-26T22:40:25.431869Z"
                writerId: zxt0iwjq8y7tam46u9cb5clnn6qihimn
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 16
            "4": 3.11.5
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.95
checkpoint:
    value: null
context_length:
    value: 256
cosine_cycle_iters:
    value: 2
d_ff:
    value: 1024
d_model:
    value: 256
debug_subset_tokens:
    value: null
device:
    value: null
eval_interval:
    value: 250
eval_iters:
    value: 100
exp_name:
    value: null
grad_clip:
    value: 1
log_interval:
    value: 10
lr:
    value: 0.0006
max_iters:
    value: 2
max_new_tokens:
    value: 100
min_lr:
    value: 6e-05
mode:
    value: train
no_wandb:
    value: false
num_heads:
    value: 8
num_layers:
    value: 6
out_dir:
    value: out
prompt:
    value: The meaning of life is
rope_theta:
    value: 10000
save_interval:
    value: 1000
tags:
    value: null
temperature:
    value: 0.8
top_p:
    value: 0.9
train_data:
    value: data/tiny_stories_train.bin
val_data:
    value: data/tiny_stories_val.bin
vocab_size:
    value: 50257
wandb_project:
    value: transformer-training
warmup_iters:
    value: 200
weight_decay:
    value: 0.1
